### ISSUE TITLE
Development Environment: mysql locally or remote?

### ISSUE THREAD

**Issue by stayhero** [imalexsq/youPM#3]
I usually develop using my local mysql-server (dedicated server in our office). The database.yml looks as this:

```
development:
  username: rails
  password: xxx 
  adapter: mysql2
  encoding: utf8
  host: local_mysql
  database: project_dev

production:
  username: rails
  password: xxx
  adapter: mysql2
  encoding: utf8
  host: liveserver.mycompany.com
  database: project_live
```

Because sometimes I want to work from home, I add  

```
11.122.222.222  local_mysql
```

to my /etc/hosts file. That way I'm always talking to the right mysql-server (depending on where I am).

Ryanicle suggested that we should work on the live mysql-server because it's easier to work on the same database and sample data (that's true). Because of that for this project I setup the database.yml to talk with the mysql-server at Amazon.

Unfortunately this feels slow on my system ( maybe because it's a micro instance, maybe because I'm in Germany and the connection is too slow, and maybe because Rails connects to the database on each page view and every page impression of a javascript and css file in development mode).

I added a new environment development_local so that I can still work on my local mysql-server. I would love to change it so that by default we'd develop on our local mysql-server, and for everyone who doesn't want to use a local server they could use the development_remote environment.

But this depends on how you guys prefer to work? Connecting to the remote mysql-server at Amazon, or using a database copy on your local system?
